import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from './layout'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div>
          <Layout />
            <div className={styles.world}>
              <h1>This is my page</h1>
            </div>
        </div>
      </main>

     
    </div>
  )
}
